name: Release Package

on:
  push:
    branches: [main]

permissions:
  id-token: write
  contents: write

jobs:
  release:
    name: Release Package
    uses: juitnow/workflows-public/.github/workflows/release.yml@main
    secrets:
      AUTO_UPDATES_APP_ID: ${{ secrets.AUTO_UPDATES_APP_ID }}
      AUTO_UPDATES_APP_PRIVATE_KEY: ${{ secrets.AUTO_UPDATES_APP_PRIVATE_KEY }}
      EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
      EMAIL_SERVER: ${{ secrets.EMAIL_SERVER }}
      EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME }}
