name: &name Automatic Updates (with DB)

on: workflow_call

jobs:
  auto-update:
    runs-on: ubuntu-latest
    name: *name

    services:
      postgres:
        !include ../services/postgres.yml

    steps:
      - !include ../steps/checkout.yml
      - !include ../steps/setup-node.yml
      - !include ../steps/auto-update-auth.yml
      - !include ../steps/auto-update.yml
      - !include ../steps/email.yml
