name: &name Automatic Updates

on:
  workflow_call:
    secrets:
      git_token:
        required: true

jobs:
  auto-update:
    runs-on: ubuntu-latest
    name: *name

    steps:
      - !include ../steps/checkout.yml
      - !include ../steps/setup-node.yml
      - !include ../steps/auto-update.yml
      - !include ../steps/email.yml
