name: &name Automatic Updates (with DB)

on:
  workflow_call:
    secrets:
      git_token:
        required: true

jobs:
  auto-update:
    runs-on: ubuntu-latest
    name: *name

    services:
      postgres:
        !include ../services/postgres.yml

    steps:
      - !include ../steps/checkout.yml
      - !include ../steps/setup-node.yml
      - !include ../steps/auto-update.yml
