name: &name Automatic Updates (with DB)

on:
  workflow_call:
    secrets:
      AUTO_UPDATES_APP_ID:
        required: true
      AUTO_UPDATES_APP_PRIVATE_KEY:
        required: true
      EMAIL_SERVER:
        required: true
      EMAIL_PORT:
        required: false
      EMAIL_USERNAME:
        required: true
      EMAIL_PASSWORD:
        required: true

jobs:
  auto-update:
    runs-on: ubuntu-latest
    name: *name

    services:
      postgres:
        !include ../services/postgres.yml

    steps:
      - !include ../steps/setup-node.yml
      - !include ../steps/auto-update-auth.yml
      - !include ../steps/auto-update-checkout.yml
      - !include ../steps/auto-update.yml
      - !include ../steps/email.yml
