name: &name Build Package

on:
  workflow_call:
    secrets:
      git_token:
        required: false
    inputs:
      workspaces:
        type: boolean
        required: false
        default: false

jobs:
  build:
    runs-on: ubuntu-latest
    name: *name

    steps:
      - !include ../steps/checkout.yml
      - !include ../steps/setup-node.yml
      - !include ../steps/build.yml
