name: &name Release Package

on:
  workflow_call:
    secrets:
      git_token:
        required: false
      npm_token:
        required: true
    inputs:
      workspaces:
        type: boolean
        required: false
        default: false

jobs:
  release:
    runs-on: ubuntu-latest
    name: *name

    steps:
      - !include ../steps/checkout.yml
      - !include ../steps/setup-node.yml
      - !include ../steps/build.yml
      - !include ../steps/publish.yml
