name: &name Release Package

on:
  workflow_call:
    secrets:
      git_token:
        required: true
      npm_token:
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    name: *name

    steps:
      - !include ../steps/checkout.yml
      - !include ../steps/setup-node.yml
      - !include ../steps/build.yml
      - !include ../steps/publish.yml
