name: &name Release Package

on:
  workflow_call:
    secrets:
      EMAIL_SERVER:
        required: true
      EMAIL_PORT:
        required: false
      EMAIL_USERNAME:
        required: true
      EMAIL_PASSWORD:
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    name: *name

    steps:
      - !include ../steps/checkout.yml
      - !include ../steps/setup-node.yml
      - !include ../steps/build.yml
      - !include ../steps/publish.yml
      - !include ../steps/email.yml
