name: &name Release Package (with DB)

on:
  workflow_call:
    secrets:
      EMAIL_SERVER:
        required: true
      EMAIL_PORT:
        required: false
      EMAIL_USERNAME:
        required: true
      EMAIL_PASSWORD:
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    name: *name

    services:
      postgres:
        !include ../services/postgres.yml

    steps:
      - !include ../steps/checkout.yml
      - !include ../steps/setup-node.yml
      - !include ../steps/build.yml
      - !include ../steps/publish.yml
      - !include ../steps/email.yml
