# ============================================================================ #
# BUILD PACKAGE                                                                #
# ---------------------------------------------------------------------------- #
# Simply run a build, no fuss, no sweat...                                     #
# ============================================================================ #

name: Build Package
run: |
  npm clean-install ${{ inputs.workspaces && '--include-workspace-root --workspaces' || '' }}
  npm run build
env:
  PGPASSWORD: github
  PGHOST: localhost
  PGUSER: github
  PGPORT: 5432
