# ============================================================================ #
# BUILD PACKAGE                                                                #
# ---------------------------------------------------------------------------- #
# Simply run a build, no fuss, no sweat...                                     #
# ============================================================================ #

name: Build Package
run: |
  npm clean-install
  npm run build
